"""empty message

Revision ID: 14712efb8887
Revises: 866e4685b105
Create Date: 2026-04-04 00:18:10.829541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14712efb8887'
down_revision = '866e4685b105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
