"""empty message

Revision ID: 15d4814ae890
Revises: 283871bdd94d
Create Date: 2026-04-04 02:58:59.137884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d4814ae890'
down_revision = '283871bdd94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
