"""empty message

Revision ID: 283871bdd94d
Revises: 716bd4089a62
Create Date: 2026-04-04 02:58:19.548705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283871bdd94d'
down_revision = '716bd4089a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
