"""empty message

Revision ID: 2ace41014fb7
Revises: 44b4e851221e
Create Date: 2026-04-04 00:11:43.200203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ace41014fb7'
down_revision = '44b4e851221e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
