"""empty message

Revision ID: 35369856c8c0
Revises: e120d2b60534
Create Date: 2026-04-04 02:54:20.357085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35369856c8c0'
down_revision = 'e120d2b60534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
