"""empty message

Revision ID: 386baed59dc5
Revises: 47b98290a359
Create Date: 2026-04-04 15:37:14.733610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386baed59dc5'
down_revision = '47b98290a359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=0)
        batch_op.drop_constraint('fk_room_task_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_room_task_id', 'task', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint('fk_room_task_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_room_task_id', 'task', ['task_id'], ['id'])
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
