"""empty message

Revision ID: 4da1e091e178
Revises: 35369856c8c0
Create Date: 2026-04-04 02:56:51.690750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da1e091e178'
down_revision = '35369856c8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
