"""empty message

Revision ID: 532bad7299ac
Revises: 55cb38367645
Create Date: 2026-04-04 00:32:31.629950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532bad7299ac'
down_revision = '55cb38367645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
