"""empty message

Revision ID: 6c721b88f2d2
Revises: 93636544842a
Create Date: 2026-03-06 22:33:18.460202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c721b88f2d2'
down_revision = '93636544842a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_result', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('music', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('music')
        batch_op.drop_column('show_result')

    # ### end Alembic commands ###
