"""empty message

Revision ID: 7065878dd789
Revises: 6c721b88f2d2
Create Date: 2026-03-17 09:09:32.194476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7065878dd789'
down_revision = '6c721b88f2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_question', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('current_question')

    # ### end Alembic commands ###
