"""empty message

Revision ID: 716fc8880eb1
Revises: 80cc5128a274
Create Date: 2026-04-04 01:27:28.439129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716fc8880eb1'
down_revision = '80cc5128a274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
