"""empty message

Revision ID: 93328b11b0ed
Revises: 532bad7299ac
Create Date: 2026-04-04 00:41:25.856187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93328b11b0ed'
down_revision = '532bad7299ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
