"""empty message

Revision ID: 93636544842a
Revises: ced68a34bbf0
Create Date: 2026-02-12 15:57:20.517145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93636544842a'
down_revision = 'ced68a34bbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
