"""empty message

Revision ID: 99f0f0e83b54
Revises: 93328b11b0ed
Create Date: 2026-04-04 00:42:24.774260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f0f0e83b54'
down_revision = '93328b11b0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('active_test',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
