"""empty message

Revision ID: e7802976c0ad
Revises: 7065878dd789
Create Date: 2026-03-17 22:51:49.048355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7802976c0ad'
down_revision = '7065878dd789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_room_task_id', 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint('fk_room_task_id', type_='foreignkey')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
